name: country_list_app
description: A new Flutter project.

publish_to: "git"

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.0
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  firebase_core: ^0.7.0
  flutter_bloc: ^6.1.1
  freezed: ^0.12.7
  google_fonts: ^1.1.1
  scrollable_positioned_list: ^0.1.9
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.13
  lint: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
