name: country_list_app
description: A new Flutter project.

publish_to: "git"

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.0
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  firebase_core: ^0.7.0
  flutter_bloc: ^6.1.1
  freezed: ^0.12.7
  google_fonts: ^1.1.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.13
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.2.7
  lint: ^1.3.0

flutter_icons:
  image_path_android: "assets/countries-icon.png"
  image_path_ios: "assets/countries-icon.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/countries-splash.png"
  color_dark: "#000000"
  image_dark: "assets/countries-splash.png"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/
